# -*- coding: utf-8 -*-
"""anomaly_detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-zgX-6WnyGkd3FzRODp0_h5R-eDP4C5N
"""

import pandas as pd
from sklearn.ensemble import IsolationForest

df = pd.read_csv('dealer_kpi_with_scores.csv')
df['month'] = pd.to_datetime(df['month'])

features = ['model_wise_cr', 'sales_advisor_cr', 'market_share', 'ssi', 'csat',
            'monthly_sales', 'booking_pipeline', 'accessories_per_car',
            'monthly_accessories_sales', 'cptv', 'tat_complaint_resolution', 'composite_score']

X = df[features]

model = IsolationForest(n_estimators=100, contamination=0.05, random_state=42)
df['anomaly'] = model.fit_predict(X)
df['anomaly_label'] = df['anomaly'].map({1: 'Normal', -1: 'Anomaly'})

df.to_csv('dealer_kpi_with_anomalies.csv', index=False)

anomalies = df[df['anomaly'] == -1]
print(f"Total rows: {len(df)}")
print(f"Anomalies: {len(anomalies)} ({len(anomalies)/len(df)*100:.1f}%)")
print(f"Dealers flagged: {anomalies['dealer_id'].nunique()}")
print("\nFile saved: dealer_kpi_with_anomalies.csv")