# -*- coding: utf-8 -*-
"""composite_scoring

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sEediMB1Q9atNy6TSgh4PsBfBCntDZWG
"""

import pandas as pd
import numpy as np

df_kpi = pd.read_csv('dealer_monthly_kpi.csv')
df_kpi['month'] = pd.to_datetime(df_kpi['month'])

weights = {
    'model_wise_cr': 0.15, 'sales_advisor_cr': 0.15, 'market_share': 0.10,
    'ssi': 0.10, 'csat': 0.10, 'monthly_sales': 0.10, 'booking_pipeline': 0.05,
    'accessories_per_car': 0.05, 'monthly_accessories_sales': 0.05,
    'cptv': -0.10, 'tat_complaint_resolution': -0.05
}

def normalize(series, reverse=False):
    if reverse:
        return 100 - ((series - series.min()) / (series.max() - series.min()) * 100)
    return (series - series.min()) / (series.max() - series.min()) * 100

scores = pd.DataFrame()
scores['dealer_id'] = df_kpi['dealer_id']
scores['month'] = df_kpi['month']

for col, w in weights.items():
    scores[f'{col}_n'] = normalize(df_kpi[col], reverse=(w < 0))

scores['composite_score'] = 0
for col, w in weights.items():
    scores['composite_score'] += scores[f'{col}_n'] * abs(w)

scores['composite_score'] = scores['composite_score'].round(1)

df_final = df_kpi.merge(scores[['dealer_id', 'month', 'composite_score']], on=['dealer_id', 'month'])
df_final.to_csv('dealer_kpi_with_scores.csv', index=False)

latest = df_final['month'].max()
latest_data = df_final[df_final['month'] == latest][['dealer_id', 'composite_score']].sort_values('composite_score')

print(f"\nBottom 10 Dealers ({latest.strftime('%b %Y')}):")
print(latest_data.head(10).to_string(index=False))
print("\nFile saved: dealer_kpi_with_scores.csv")