# -*- coding: utf-8 -*-
"""counterfactual_engine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sFjcrNogRu8T0zeKQYxb2bWNmjh6XiF2
"""

import pandas as pd
import numpy as np
import dice_ml
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv('dealer_kpi_with_anomalies.csv')

features = ['model_wise_cr', 'sales_advisor_cr', 'market_share', 'ssi', 'csat',
            'monthly_sales', 'booking_pipeline', 'accessories_per_car',
            'monthly_accessories_sales', 'cptv', 'tat_complaint_resolution']

X = df[features]
y = df['anomaly'].map({1: 0, -1: 1})

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X, y)

d = dice_ml.Data(dataframe=df[features + ['anomaly']], continuous_features=features, outcome_name='anomaly')
m = dice_ml.Model(model=model, backend='sklearn')
exp = dice_ml.Dice(d, m)

problem = df[df['anomaly'] == -1].iloc[0]
query = pd.DataFrame(problem[features]).T

cf = exp.generate_counterfactuals(query, total_CFs=3, desired_class=0)

print("Current values (Anomaly):")
print(query.to_string(index=False))
print("\nCounterfactuals (to become Normal):")
print(cf.cf_examples_list[0].final_cfs_df.to_string(index=False))

cf.cf_examples_list[0].final_cfs_df.to_csv('counterfactuals.csv', index=False)
print("\nFile saved: counterfactuals.csv")