# -*- coding: utf-8 -*-
"""generate_dealer_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13uFID2GtxJDnadxm2vvp0vpNnGM8ySmD
"""

import pandas as pd
import numpy as np

np.random.seed(42)

cities = ['Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Hyderabad', 'Pune', 'Ahmedabad', 'Kolkata',
          'Jaipur', 'Lucknow', 'Surat', 'Nagpur', 'Indore', 'Bhopal', 'Patna', 'Vadodara',
          'Ludhiana', 'Agra', 'Nashik', 'Ranchi', 'Meerut', 'Raipur', 'Amritsar', 'Aurangabad', 'Jodhpur']

regions_map = {'Mumbai':'West','Pune':'West','Ahmedabad':'West','Surat':'West','Nagpur':'West',
               'Nashik':'West','Aurangabad':'West','Vadodara':'West','Indore':'West',
               'Delhi':'North','Jaipur':'North','Lucknow':'North','Ludhiana':'North',
               'Agra':'North','Meerut':'North','Amritsar':'North','Jodhpur':'North',
               'Bangalore':'South','Chennai':'South','Hyderabad':'South',
               'Kolkata':'East','Patna':'East','Ranchi':'East','Raipur':'East','Bhopal':'East'}

states_map = {'Mumbai':'Maharashtra','Pune':'Maharashtra','Nagpur':'Maharashtra','Nashik':'Maharashtra',
              'Aurangabad':'Maharashtra','Ahmedabad':'Gujarat','Surat':'Gujarat','Vadodara':'Gujarat',
              'Delhi':'Delhi','Bangalore':'Karnataka','Chennai':'Tamil Nadu','Hyderabad':'Telangana',
              'Kolkata':'West Bengal','Jaipur':'Rajasthan','Jodhpur':'Rajasthan','Lucknow':'Uttar Pradesh',
              'Agra':'Uttar Pradesh','Meerut':'Uttar Pradesh','Ludhiana':'Punjab','Amritsar':'Punjab',
              'Patna':'Bihar','Ranchi':'Jharkhand','Raipur':'Chhattisgarh','Bhopal':'Madhya Pradesh','Indore':'Madhya Pradesh'}

dealer_types = ['3S Facility', '2S Facility', 'Authorized Showroom']

dealers = []
for i in range(1, 501):
    city = np.random.choice(cities)
    dealers.append({'dealer_id': f'D{i:03d}', 'dealer_name': f'AutoWorld {i}',
                    'city': city, 'region': regions_map[city], 'state': states_map[city],
                    'established_year': np.random.randint(1990, 2024),
                    'dealer_type': np.random.choice(dealer_types, p=[0.3, 0.4, 0.3]),
                    'owner_name': f'Owner {i}'})
df_dealers = pd.DataFrame(dealers)

months = pd.date_range(start='2023-01-01', periods=24, freq='MS')
kpi_data = []

for _, d in df_dealers.iterrows():
    base_cr, base_sales = np.random.uniform(20, 55), np.random.randint(30, 200)
    base_acc, base_cptv = np.random.uniform(1500, 10000), np.random.uniform(0.5, 6)
    base_tat, base_ssi = np.random.uniform(1, 10), np.random.uniform(65, 98)
    base_csat, base_ms = np.random.uniform(2.5, 5.0), np.random.uniform(3, 30)
    is_problem = d['dealer_id'] in [f'D{i:03d}' for i in np.random.choice(range(1,501), 60, replace=False)]

    for idx, month in enumerate(months):
        boost = 1.0
        if month.month in [10,11]: boost = np.random.uniform(1.15, 1.35)
        elif month.month in [4,5]: boost = np.random.uniform(0.85, 0.95)
        noise = np.random.uniform(-0.12, 0.12)
        decline = 1.0 - (idx * 0.015) if is_problem else 1.0
        drop = np.random.uniform(0.45, 0.75) if (is_problem and np.random.random() < 0.15) else 1.0

        kpi_data.append({
            'dealer_id': d['dealer_id'], 'month': month,
            'model_wise_cr': round(np.clip(base_cr*decline*drop*boost*(1+noise), 5, 70), 1),
            'sales_advisor_cr': round(np.clip(base_cr*0.78*decline*drop*boost*(1+noise), 3, 65), 1),
            'market_share': round(np.clip(base_ms*decline*boost*(1+noise), 1, 40), 1),
            'ssi': round(np.clip(base_ssi*(1+noise*0.4), 50, 100), 0),
            'csat': round(np.clip(base_csat*(1+noise*0.3), 2.0, 5.0), 1),
            'monthly_sales': int(np.clip(base_sales*decline*drop*boost*(1+noise), 5, 350)),
            'booking_pipeline': int(np.clip(base_sales*0.65*decline*boost*(1+noise*2.5), 2, 280)),
            'accessories_per_car': round(np.clip(base_acc*decline*(1+noise), 500, 18000), 0),
            'monthly_accessories_sales': round(np.clip(base_acc*base_sales*0.6*decline*boost*(1+noise), 5000, 2500000), 0),
            'cptv': round(np.clip(base_cptv*(2-decline)*(1+noise), 0.1, 15), 1),
            'tat_complaint_resolution': round(np.clip(base_tat*(2-decline)*(1+noise*0.6), 0.5, 20), 1)
        })

df_kpi = pd.DataFrame(kpi_data)
df_dealers.to_csv('dealer_master.csv', index=False)
df_kpi.to_csv('dealer_monthly_kpi.csv', index=False)

print(f"Dealers: {len(df_dealers)} | Monthly rows: {len(df_kpi)} | Files saved.")