# -*- coding: utf-8 -*-
"""xai_shap

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1caaTZOWqFMdWJg-1ZClUO2XOI1BfmRy4
"""

import pandas as pd
import numpy as np
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import shap
import matplotlib.pyplot as plt

df = pd.read_csv('dealer_kpi_with_anomalies.csv')

features = ['model_wise_cr', 'sales_advisor_cr', 'market_share', 'ssi', 'csat',
            'monthly_sales', 'booking_pipeline', 'accessories_per_car',
            'monthly_accessories_sales', 'cptv', 'tat_complaint_resolution']

X = df[features]
y = df['anomaly'].map({1: 0, -1: 1})

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = XGBClassifier(n_estimators=100, max_depth=5, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, y_pred):.3f}")

explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X_test)

shap.summary_plot(shap_values, X_test, show=False)
plt.savefig('shap_summary.png', dpi=150, bbox_inches='tight')
plt.close()

importance = pd.DataFrame({'feature': features, 'importance': np.abs(shap_values).mean(0)})
importance = importance.sort_values('importance', ascending=False)
print("\nTop 5 drivers of anomaly:")
print(importance.head(5).to_string(index=False))
print("\nSHAP plot saved: shap_summary.png")